import Body from "@/components/Body";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>teleport</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-body-gray flex flex-col">
        <Header />
        <Body />
        <Footer />
      </main>
    </>
  );
}
